### ISSUE TITLE
Bug in line 159 of popup.js

### ISSUE THREAD

**Issue by chaosking121** [roboticsound/Pulsarr#10]
I'm new to javascript and decided to repurpose Pulsarr for another application I'm working on as a first project in the language. While doing so, I think I found a bug in the post method in popup.js. 

Line 159 of popup.js reads:
`results = { "text": JSON.parse(http.responseText), "status": http.status };`

I think it should read the same as line 131: 
`var results = { "text": JSON.parse(http.responseText), "status": http.status };`

Not sure if this affects the extension in any way, but I felt it was worth pointing out since it came up in my "fork".

**Comment by chaosking121** [comment]
The post method also looks to be missing the Content-Type header:
`http.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");`

And I could not for the life of my get my parameters sent using JSON.stringify. I *think* this error was due to my inexperience with javascript though. I was only able to get it working by manually writing a parameter string and sending that directly. But once again, I think that's a problem on my end.

**Comment by roboticsound** [comment]
> I think it should read the same as line 131:
var results = { "text": JSON.parse(http.responseText), "status": http.status };

Yeah you are right and has been corrected.

>The post method also looks to be missing the Content-Type header:

Less of a mistake as I am unsure that it is really required but I will add it for good measure :)
