### ISSUE TITLE
Some IMDb titles not being detected

### ISSUE THREAD

**Issue by seriosbrad** [roboticsound/Pulsarr#11]
http://www.imdb.com/title/tt4961380

http://www.imdb.com/title/tt5642692

Here's two quick movies that Pulsarr is not picking up.  The first one I was actively looking for, then I started clicking into the "People who liked this also liked..." section and came across more that weren't working.

**Comment by roboticsound** [comment]
I am going to close this one as is seems that the first link is now working and the second maybe is not because it is a 20 min short. The searching itself is done by radarr, not pulsarr so it may be worth raising it with them.
