### ISSUE TITLE
Ability to select 'Path' when adding Movies

### ISSUE THREAD

**Issue by 0xdevalias** [roboticsound/Pulsarr#13]
It would be cool if the path was selectable when adding movies

**Comment by roboticsound** [comment]
I have thought about this one but I want to keep the UI as simple as possible. Do you not keep all your movies is the same root folder?

**Comment by alias1** [comment]
I do, but I guess from the UX perspective I was more concerned about the ambiguity (how will it add it, what folder, is this even up to date for the latest version) than I would have been by seeing another drop down box (that I could look past if it was correct).

If not this, maybe choosing the default in the options, or some clarifying text around it somewhere?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by roboticsound** [comment]
OK thank you for your input, yes I can see your point. I think though for now I will add this as a config option, though if it is wanted by enough people I guess it could be added to the main popup (or perhaps could be an option that is enabled in config).

**Comment by alias1** [comment]
Config option sounds good to me. Thanks :3

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tooviral** [comment]
It'd be great if it could be a drop down option per movie

**Comment by roboticsound** [comment]
What do you mean by a dropdown? Where would the options be set?

**Comment by tooviral** [comment]
I'm not sure its just I have three paths  "Movies, Kids Movies, Anime Movies"  A drop down under profile to choose which path it saves to.

**Comment by idiidi** [comment]
I keep all my movies in a different folders. So an option to select the location when adding the movie would be great.

**Comment by gill7719** [comment]
+1 on this feature.
Adding a dropdown right under Profile with the "Paths" that are defined in Radarr would be perfect.

**Comment by roboticsound** [comment]
Should be addressed by #28
