### ISSUE TITLE
Permanent Window

### ISSUE THREAD

**Issue by monkeyslapper** [roboticsound/Pulsarr#24]
It works Fine, but i would the popup window be a permanent window. I like to multitask and when i see the movie i like to capture i have to wait for the window to load and populate the information. During this time I would like to be able to go to another window or tab to do something else while it loads. Its not a long time. But enough to say I can do something in the mean time. Any way to change this or have an option turn on feature.

Thanks.

**Comment by roboticsound** [comment]
Unfortunately this is not something that chrome extensions supports, so at this time I am unable to add this.
