### ISSUE TITLE
Cannot add movies from IMDB on 2.0

### ISSUE THREAD

**Issue by sp1ti** [roboticsound/Pulsarr#31]
Since the extension updated and I've readded the radarr configuration I cannot add any movies from IMDB. The flyout is stuck at the spinner.

I see the following error in console
```
popup.js:215 Uncaught TypeError: Cannot read property 'radarr' of undefined
    at Pulsarr.portConfigToV2 (popup.js:215)
    at init (popup.js:593)
    at popup.js:634
```

Running radarr via basic localhost/no auth/default.

**Comment by sp1ti** [comment]
A fresh install solved the issue. The main thing that changed from what I can see is that I only have a single LocalStorage entry now (`pulsarrConfig`). Before the uninstall I had all ?keys from the json also as "main" entries in there.

**Comment by roboticsound** [comment]
Yeah, there was an error in the code to migrate to the new version. I have released a hotfix for this but in the meantime if anyone is experiencing similar issues, please just reinstall Pulsarr it will resolve this.
