### ISSUE TITLE
Can't add movies when Min Avil is set to "In Cinemas" or "Physical/Web"

### ISSUE THREAD

**Issue by zebbe152** [roboticsound/Pulsarr#32]
I can't add movies when Min Avil is set to "In Cinemas" or "Physical/Web". Pulsarr says "Failed to add movie! Please check it is not already in your collection."

It works if I switch to either "Announced" or "Pre DB".

I'm running the new 2.0 update.

**Comment by roboticsound** [comment]
Hi, hmm I am unable to replicate. Could you try to remove and reinstall Pulsarr? I have changed a lot in the way that it works and this will clear any previous config.

**Comment by zebbe152** [comment]
I did that yesterday (I had to remove and then add pulsarr again in order to get it to connect with Sonarr). Did you press add movie or the magnifying glass?

It seems like the error I mentioned only occurs when I press "add movie".

I've been having this issue ever since the previous version, so it's probably not related to the 2.0 update.

**Comment by roboticsound** [comment]
Could you confirm which version of Radarr you are running? Also, is this the case with all movies?

**Comment by zebbe152** [comment]
Radarr version 0.2.0.852

I got this from the Radarr log:

17-9-16 17:42:41.1|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Invalid Path
 -- Invalid Path

I was able to add a movie by pressing the magnifying glass a couple of times, but that doesn't work now either.

It doesn't matter which movie I choose on IMDB.

Very strange...

**Comment by roboticsound** [comment]
Did you enter a path in the Pulsarr config or have you left it blank?

**Comment by zebbe152** [comment]
The root path is blank in Pulsarr.

**Comment by roboticsound** [comment]
OK well at least it is working for you just now. This will be getting addressed soon though as I believe this will be solved by #27.
