### ISSUE TITLE
Update Firefox Addon

### ISSUE THREAD

**Issue by dedors** [roboticsound/Pulsarr#40]
Firefox still running 1.3.1, and with that no support for sonarr yet. There is no other firefox addon for sonarr, so updating the addon to 2.0 would be much appreciated.

**Comment by roboticsound** [comment]
Hi,
Yeah sorry I have been busy with other projects but I have made some updates and I have now pushed to both chrome and firefox. I will close this but please open a new issue if any are discovered with the new version.
