### ISSUE TITLE
Feature request - support for Filmaffinity

### ISSUE THREAD

**Issue by R91g** [roboticsound/Pulsarr#41]
Hi,
First thank to roboticsound for her great job and all others contributors.

I want support for https://www.filmaffinity.com
Filmaffinity is more famous website with the mayor TV and movie database in Spanish.

Thanks.

**Comment by roboticsound** [comment]
Hi R91g, unfortunately due to the way Pulsarr works, this is not something I am able to support at this time. If at any stage filmaffinity begin to provide links to IMDB ot TMDB, I may be able to revisit this.

**Comment by R91g** [comment]
Hi roboticsound,
Ok, thank you for your answer.
