### ISSUE TITLE
Pulsarr just spins when you click on it.

### ISSUE THREAD

**Issue by slydog3333** [roboticsound/Pulsarr#64]
by right clicking and inspecting, this error comes up:
Uncaught (in promise) TypeError: Cannot read property 'overview' of undefined
    at Pulsarr.init (popup.js:79)
    at popup.js:746

Doesn't work in Chromium Version 69.0.3445.0
or the current version of Chrome

Looks like the firefox extension doesn't work either. Is this dead?

**Comment by piejanssens** [comment]
It works fine here. 
Which version of Pulsarr? Try installing the latest one by installing the zip from git instead.

**Comment by slydog3333** [comment]
Yeah my wife said it started working again a few weeks ago. Not sure if it updated or what.
