### ISSUE TITLE
Memory usage seems to be high at 200MB

### ISSUE THREAD

**Issue by jcspradley** [roboticsound/Pulsarr#8]
Extension appears to be using 200MB just sitting there idling. 

![pulsarr](https://cloud.githubusercontent.com/assets/26350308/24076386/6277f1d0-0c05-11e7-89c0-c8931da23710.png)

Mac OSX 10.12.3 
Chrome Version 57.0.2987.98 (64-bit)

**Comment by roboticsound** [comment]
I'm not quite sure what is going on here. Is it always like this even after a restart? I have not tested on Mac but for me it uses about 1kB when idling and around 30kB when working.

**Comment by jcspradley** [comment]
I've been keeping an eye on it to try and provide you with a little more info. After a restart, without having used it, it was using approximately 45-47MB. After using it once it jumped up to 120MB and then came back down to 97.9MB. After using it a second time it jumped up to about 197MB and then came back down to 146MB. After a third use it actually didn't jump up at all and then went down to 137MB. I don't know if any of that is helpful or not. Let me know if there's anything I can provide.

**Comment by roboticsound** [comment]
I still haven't got round to testing this on Mac OSX. Can anyone confirm that this is still an issue?

**Comment by roboticsound** [comment]
Closing as no further issues have been reported. Will reopen later if necessary.
